config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  get '/my_bookings', to: 'bookings#my_bookings', as: 'my_bookings'
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORIES = ['Luxury', 'Economy', 'Electric']

  def unavailable_dates
    bookings.pluck(:starting_date, :ending_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    @car.bookings
    authorize @booking

    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy

    redirect_to my_bookings_path
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
    authorize @bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date, :car_id, :bookings_count)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]

  def index
    if params[:category].present?
      @cars = policy_scope(Car).where(category: params[:category])
    else
      @cars = policy_scope(Car)

    end

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: helpers.asset_url('car.png')
      }
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    authorize @car
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user

    authorize @car
    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
    authorize @car
  end

  def update
    @car = Car.find(params[:id])
    authorize @car
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car = Car.find(params[:id])
    authorize @car
    @car.destroy

    redirect_to @car
  end

  private

  def car_params
    params.require(:car).permit(:name, :model, :address, :year, :category, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<div class="container-fluid">
<%= link_to '+ New Car', new_car_path, class: 'btn btn-green my-4' %>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">My Bookings</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My Cars</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active mx-5" id="home" role="tabpanel" aria-labelledby="home-tab"><div class="d-flex justify-content-around flex-wrap ">
      <% @bookings.each do |booking| %>
        <%= link_to car_path(booking.car.id), class: 'booking-text' do%>
          <div class="card-product my-4 booking-text ">
            <%= cl_image_tag booking.car.photo.key, class: 'car-photo' %>
            <div class="card-product-infos">
              <h2><%= booking.car.name %> <%= booking.car.model %> <%= booking.car.year %></h2>
              <div>
              <div class="d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Where?</span><p class="show-info"><%= booking.car.address%></p></div>

              <div class="d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> What?</span><p class="show-info"><%= booking.car.category %></p></div>
              <div class="d-flex show-question"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Price:</span><p class="show-info">AED<%= booking.car.price %></p></div>
            </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    </div>
    <div class="tab-pane fade mx-5" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="d-flex justify-content-around flex-wrap">
      <% current_user.cars.each do |car|%>
        <%= link_to car_path(car.id), class: 'booking-text' do%>
            <div class="card-product my-4 booking-text ">
              <%= cl_image_tag car.photo.key, class: 'car-photo' %>
              <div class="card-product-infos">
                <h2><%= car.name %> <%= car.model %> <%= car.year %></h2>
                <div>
                <div class="d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Where?</span><p class="show-info"><%= car.address%></p></div>

                <div class="d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> What?</span><p class="show-info"><%= car.category %></p></div>
                <div class="d-flex show-question"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Price:</span><p class="show-info">AED<%= car.price %></p></div>
              </div>
              </div>
            </div>
          <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>



<div class="footer">
  <div class="container">
    <div class="row align-items-center g-0 py-2">
      <!-- Desc -->
      <div class="col-md-6 col-12 text-left text-md-start">
        <span>© 2021 Rent-a-Car Company
        <hr>
        Address: Businesss Bay, Dubai</span>
      </div>
       <!-- Links -->
      <div class="col-12 col-md-6">
        <nav class="nav nav-footer justify-content-center justify-content-md-end">
          <a class="nav-link active ps-0" href="#">Privacy</a>
          <a class="nav-link" href="#">Terms </a>
          <a class="nav-link" href="#">Feedback</a>
          <a class="nav-link" href="#">Support</a>
        </nav>
      </div>
    </div>
  </div>
  <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for([@car, @booking]) do |f| %>
  <%= f.input :starting_date, as: :string, input_html: {class: "datepicker"}%>
  <%= f.input :ending_date, as: :string, input_html: {class: "datepicker"}%>
  <%= f.submit "book", class: "btn btn-primary btn-lg btn-block btn-booking" %>
<% end %>

app/views/cars/_info_window.html.erb
<h2><%= car.name %></h2>
<p><%= car.address %></p>

app/views/cars/edit.html.erb
<div class="container mb-2">
<h2>Updated your listed car:</h2>
  <%= link_to 'Back', cars_path, class: 'btn btn-secondary mb-2' %>
  <%= simple_form_for [@car] do |f| %>
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :year %>
      <%= f.input :category %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn-green w-100" %>
    <% end %>
</div>

app/views/cars/index.html.erb
<div class="booking-text">
  <div class="d-flex align-items-center mt-4 margin-left booking-text fix-top filter-background" id="filters">
    <p class="m-0 mr-3">Filter by category:</p>
    <%= form_for cars_path, method: :get do%>
      <%= select_tag :category, options_for_select(Car::CATEGORIES) %>
      <%= submit_tag 'Apply', class: 'btn-green py-1' %>
    <% end %>
    <%= link_to cars_path, class: 'btn btn-danger ml-3 py-1 rounded-border' do%>
      <p class="m-0"><i class="fas fa-times-circle"></i> Remove Filter</p>
    <% end %>
  </div>
  <div class="row booking-text justify-content-around">
    <div class="col-6 d-flex flex-wrap booking-text">
      <% @cars.each do |car|%>
        <%= link_to car_path(car) do %>
          <div class="card-trip booking-text">
            <%= cl_image_tag car.photo.key, class: "car-photo"%>
            <div class="card-trip-infos text-left ">
              <div>
                <h2><%= car.name %> <%= car.model %></h2>
                <p><%= car.year %></p>
                <p style="font-size: 16px"><%= car.address%></p>
              </div>
              <h2 class="card-trip-pricing">AED<%= car.price %> / Day</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-5 w-100">
      <div id="map"
          class="fix-top"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>




<div class="footer">
  <div class="container">
    <div class="row align-items-center g-0 py-2">
      <!-- Desc -->
      <div class="col-md-6 col-12 text-left text-md-start">
        <span>© 2021 Rent-a-Car Company
        <hr>
        Address: Businesss Bay, Dubai</span>
      </div>
       <!-- Links -->
      <div class="col-12 col-md-6">
        <nav class="nav nav-footer justify-content-center justify-content-md-end">
          <a class="nav-link active ps-0" href="#">Privacy</a>
          <a class="nav-link" href="#">Terms </a>
          <a class="nav-link" href="#">Feedback</a>
          <a class="nav-link" href="#">Support</a>
        </nav>
      </div>
    </div>
  </div>
  <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">

  <h1>New car to be added:</h1>

  <%= simple_form_for [@car] do |f| %>
      <%= f.input :name %>
      <%= f.input :model %>
      <%= f.input :year %>
      <%= f.input :category, collection: Car::CATEGORIES %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn-green w-100" %>
    <% end %>


  <%= link_to 'Back', cars_path, class: 'btn btn-secondary mt-5' %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between my-4">
  <div class="back-btn"><i class="fas fa-chevron-left"></i> <%= link_to 'Back', cars_path, class: 'no-decorations'%></div>
  <div class="d-flex justify-content">
    <% if policy(@car).edit? %>
    <div class="back-btn blue">
      <i class="fas fa-chevron-down"></i>
        <%= link_to 'Edit',
                    edit_car_path(@car),
                    class: 'no-decorations'
        %>
    </div>
    <% end %>
    <% if policy(@car).destroy? %>
    <div class="back-btn red">
      <i class="fas fa-trash"></i>
        <%= link_to 'Delete',
                    car_path(@car),
                    method: :delete,
                    class: 'no-decorations',
                    data: { confirm: 'Are you sure ?'}
        %>
    </div>
    <% end %>
  </div>
</div>
  <div class="row">
    <div class="col-8 border-bottom mb-4">
      <%# <%= cl_image_tag @car.photo.key, height: 300, crop: :fill %>
      <div class="show-card my-5 py-3 title">
        <h1><%= @car.name%> <%= @car.model %> <%= @car.year %></h1>
      </div>
      <div>
        <div class="left-margin1 d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Where?</span><p class="show-info"><%= @car.address%></p></div>

        <div class="left-margin2 d-flex show-question mb-2"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> What?</span><p class="show-info"><%= @car.category %></p></div>
        <div class="left-margin3 d-flex show-question"><span class="pt-2 mr-3 bigger-font"><i class="fas fa-car"></i> Price:</span><p class="show-info">AED<%= @car.price %></p></div>
      </div>
      <div class="wacky-line wacky-rotation"></div>
    </div>

    <div class="col-4 mt-4 border-right border-left">
      <%= cl_image_tag @car.photo.key, class: 'car-photo negative-margin-right'%>
      <div class="show-card p-5 mt-3 py-3 color-beige booking-text">
        <%= simple_form_for [@car, @booking], data: { unavailable_dates: @car.unavailable_dates.to_json } do |f| %>
          <%= f.input :starting_date, as: :string, input_html: {class: "datepicker"}%>
          <%= f.input :ending_date, as: :string, input_html: {class: "datepicker"}%>
          <%= f.submit "Book Now", class: "btn-green btn-big" %>
        <% end %>
      </div>

    </div>
  </div>

</div>

<div class="diagonal-split-background"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentACar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%# render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1 style="text-shadow: 1px 1px 12px black;">Your dream car</h1>
    <p style="text-shadow: 1px 1px 12px black;">With you wherever you are</p>
    <%= link_to 'Explore Cars', cars_path, class: 'btn-green', style: 'box-shadow: 0px 0px 15px black;' %>
  </div>
</div>

<div class="container">
  <h2 class="my-4">Hassle-free renting, wherever you are from the confort of your mobile phone.</h2>
  <div class="d-flex">
    <div style="box-shadow: 0px 0px 3px black;" class="p-4 home-info text-center m-4">
      <h2>Your dream car, at the click of a button</h2>
      <img src="https://images.unsplash.com/photo-1502877338535-766e1452684a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80" alt="" class="car-photo mt-4">
      <p class="mt-4">Easily see and rent the car of your dreams from the comfort of your home. Amazing responsive design as fast as the car you would be riding.</p>
    </div>
    <div style="box-shadow: 0px 0px 3px black;" class="p-4 home-info text-center m-4">
      <h2>The nightmare of going to a car dealership is over.</h2>
      <img src="https://images.unsplash.com/photo-1489824904134-891ab64532f1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1189&q=80" alt="" class="car-photo mt-4">
      <p class="mt-4">No more paperwork, long hours at the dealership and paying redicilous fees. Control the way you want to rent, with no extra hidden costs.</p>
    </div>
  </div>

  <div style="box-shadow: 0px 0px 3px black;" class="p-4 text-center m-4">
    <h3 class="my-5">Are you ready to experience the way car rental should be? </h3>
    <p><%= link_to 'Explore Cars', cars_path, class: 'btn-green' %></p>
  </div>

  <div class="d-flex">
    <div class="bg-review p-5 review-card m-4" style="box-shadow: 0px 0px 3px black;">
      <div>
        <p> I got my dream car within 5 minutes. Best service ever!</p>
        <p> <em>- Paula</em></p>
      </div>

      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
    </div>

    <div class="bg-review p-5 review-card m-4" style="box-shadow: 0px 0px 3px black;">
      <div>
        <p> I had a problem with a rental. The folks at RentaCar fixed it up for me instantly!</p>
        <p> <em>- Kevin</em></p>
      </div>

      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="far fa-star gold"></i>
    </div>

    <div class="bg-review p-5 review-card m-4" style="box-shadow: 0px 0px 3px black;">
      <div>
        <p> Went on a vacation and gave my car as a rental. Setting it up took seconds and I was earning money while on a vacation. Absolutely brilliant.</p>
        <p> <em>- Jake</em></p>
      </div>

      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
      <i class="fas fa-star gold"></i>
    </div>
  </div>
</div>




<div class="footer">
  <div class="container">
    <div class="row align-items-center g-0 py-2">
      <!-- Desc -->
      <div class="col-md-6 col-12 text-left text-md-start">
        <span>© 2021 Rent-a-Car Company
        <hr>
        Address: Businesss Bay, Dubai</span>
      </div>
       <!-- Links -->
      <div class="col-12 col-md-6">
        <nav class="nav nav-footer justify-content-center justify-content-md-end">
          <a class="nav-link active ps-0" href="#">Privacy</a>
          <a class="nav-link" href="#">Terms </a>
          <a class="nav-link" href="#">Feedback</a>
          <a class="nav-link" href="#">Support</a>
        </nav>
      </div>
    </div>
  </div>
  <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row align-items-center g-0 py-2">
      <!-- Desc -->
      <div class="col-md-6 col-12 text-left text-md-start">
        <span>© 2021 Rent-a-Car Company
        <hr>
        Address: Businesss Bay, Dubai</span>
      </div>
       <!-- Links -->
      <div class="col-12 col-md-6">
        <nav class="nav nav-footer justify-content-center justify-content-md-end">
          <a class="nav-link active ps-0" href="#">Privacy</a>
          <a class="nav-link" href="#">Terms </a>
          <a class="nav-link" href="#">Feedback</a>
          <a class="nav-link" href="#">Support</a>
        </nav>
      </div>
    </div>
  </div>
  <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-border">
  <div class="container">
    <%= link_to root_path do %>
      <%= image_tag "logo2.png", class: 'height-logo'  %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <p class="dropdown-toggle cursor", id="navbarDropdown", data-toggle= "dropdown"> <%= current_user.email  %></p>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", my_bookings_path, class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn-green thin" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>